CREATE TABLE `distance_quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`clientPhone` varchar(50),
	`clientEmail` varchar(320),
	`jobType` varchar(100) NOT NULL,
	`jobAddress` text NOT NULL,
	`jobAcres` int NOT NULL DEFAULT 0,
	`crewDaysNeeded` int NOT NULL DEFAULT 1,
	`notes` text,
	`distanceMiles` int NOT NULL DEFAULT 0,
	`driveDuration` varchar(100),
	`baseDayRateCents` int NOT NULL DEFAULT 0,
	`mobSurchargeCents` int NOT NULL DEFAULT 0,
	`adjustedDayRateCents` int NOT NULL DEFAULT 0,
	`adjustedJobTotalCents` int NOT NULL DEFAULT 0,
	`pricePerAcreCents` int NOT NULL DEFAULT 0,
	`targetMarginPct` int NOT NULL DEFAULT 30,
	`status` enum('draft','sent','accepted','declined','expired') NOT NULL DEFAULT 'draft',
	`sentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `distance_quotes_id` PRIMARY KEY(`id`)
);
