CREATE TABLE `field_quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(320),
	`phone` varchar(50),
	`address` text,
	`lat` decimal(10,7),
	`lng` decimal(10,7),
	`serviceType` varchar(100),
	`acreage` decimal(8,2),
	`terrainType` varchar(100),
	`vegetationDensity` varchar(100),
	`vegetationTypes` varchar(255),
	`slopeCondition` varchar(100),
	`accessCondition` varchar(255),
	`obstacles` text,
	`proximityToStructures` text,
	`message` text,
	`photoUrls` text,
	`source` varchar(50) NOT NULL DEFAULT 'field_app',
	`aiScore` enum('strong','marginal','weak'),
	`aiSummary` text,
	`aiFlags` text,
	`aiDraftResponse` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `field_quotes_id` PRIMARY KEY(`id`)
);
