CREATE TABLE `native_quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`clientEmail` varchar(255),
	`clientPhone` varchar(30),
	`propertyAddress` varchar(500),
	`title` varchar(500) NOT NULL,
	`internalNotes` text,
	`clientMessage` text,
	`lineItems` text NOT NULL,
	`totalCents` int NOT NULL DEFAULT 0,
	`estimatedDuration` varchar(100),
	`acreage` varchar(50),
	`serviceType` varchar(100),
	`status` varchar(30) NOT NULL DEFAULT 'draft',
	`portalToken` varchar(64),
	`portalSentAt` timestamp,
	`portalViewedAt` timestamp,
	`clientAction` varchar(20),
	`clientActionAt` timestamp,
	`signatureDataUrl` text,
	`signatureTypedText` varchar(255),
	`signatureMode` varchar(10),
	`signedAt` timestamp,
	`changeRequestNote` text,
	`changeRequestAt` timestamp,
	`declineNote` text,
	`depositPaidCents` int,
	`depositPaidAt` timestamp,
	`stripeSessionId` varchar(255),
	`portalAddOns` text,
	`portalAddOnsTotalCents` int,
	`leadId` int,
	`fieldQuoteId` int,
	`distanceQuoteId` int,
	`convertedJobId` int,
	`convertedToJobAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT now(),
	`updatedAt` timestamp NOT NULL DEFAULT now() ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `native_quotes_id` PRIMARY KEY(`id`)
);
