CREATE TABLE `native_invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`jobId` int NOT NULL,
	`quoteId` int,
	`clientName` varchar(255) NOT NULL,
	`clientEmail` varchar(255),
	`clientPhone` varchar(30),
	`propertyAddress` varchar(500),
	`serviceType` varchar(100),
	`lineItems` text NOT NULL,
	`subtotalCents` int NOT NULL DEFAULT 0,
	`depositPaidCents` int NOT NULL DEFAULT 0,
	`totalCents` int NOT NULL DEFAULT 0,
	`status` enum('unpaid','sent','paid','void') NOT NULL DEFAULT 'unpaid',
	`pdfUrl` varchar(1024),
	`emailSentId` varchar(128),
	`emailSentAt` timestamp,
	`paidAt` timestamp,
	`dueDate` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `native_invoices_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `native_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`quoteId` int,
	`clientName` varchar(255) NOT NULL,
	`clientEmail` varchar(255),
	`clientPhone` varchar(30),
	`propertyAddress` varchar(500),
	`serviceType` varchar(100),
	`acreage` varchar(50),
	`totalCents` int NOT NULL DEFAULT 0,
	`lineItems` text NOT NULL,
	`status` enum('scheduled','in_progress','completed','cancelled') NOT NULL DEFAULT 'scheduled',
	`scheduledDate` timestamp,
	`completedAt` timestamp,
	`internalNotes` text,
	`invoicedCents` int,
	`invoicedAt` timestamp,
	`paidCents` int,
	`paidAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `native_jobs_id` PRIMARY KEY(`id`)
);
